# This workflow build the Docker image with the application 

name: Get configuration

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build the container application
  get_image:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    # Outputs
    outputs:
      gcc: ${{ steps.get_gcc_ver.outputs }}
      gfortran: ${{ steps.get_gfortran_ver.outputs }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Download image
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image
        run: |
          docker pull ghcr.io/${{ github.actor }}/armhpctrial:latest

      # Get versions numbers
      - name: Get GCC version
        id: get_gcc_ver
        run: |
          docker run --platform arm64 --rm -i ghcr.io/${{ github.actor }}/armhpctrial:latest gcc -dumpfullversion

      - name: Get Gfortran version
        id: get_gfortran_ver
        run: |
          docker run --platform arm64 --rm -i ghcr.io/${{ github.actor }}/armhpctrial:latest gfortran -dumpfullversion

  badge:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    needs: get_image
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: badges

      - name: Update badge
        run: |
          mkdir -p .github/badges
          cd .github/badges
          rm -f *.svg
          curl -o .github/badges/gcc.svg https://img.shields.io/badge/${{ needs.get_image.outputs.gcc }}
          curl -o .github/badges/gfortran.svg https://img.shields.io/badge/${{ needs.get_image.outputs.gfortran }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add badges/*.svg
          if git commit -m "Update badges"; then
            git push
          fi
