# This workflow build the Docker image with the application 

name: Get configuration

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build the container application
  get_image:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    # Outputs
    outputs:
      gcc: ${{ steps.get_gcc_ver.outputs.gcc }}
      gfortran: ${{ steps.get_gfortran_ver.outputs.gfortran }}
      python: ${{ steps.get_python_ver.outputs.python }}
      numpy: ${{ steps.get_numpy_ver.outputs.numpy }}
      scipy: ${{ steps.get_scipy_ver.outputs.scipy }}
      mpi4py: ${{ steps.get_mpi4py_ver.outputs.mpi4py }}
      blas: ${{ steps.get_blas_ver.outputs.blas }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # For cross-platform
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Download image
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image
        run: |
          docker pull ghcr.io/${{ github.actor }}/armhpctrial:latest

      # Get versions numbers
      - name: Get GCC version
        id: get_gcc_ver
        run: |
          docker run --platform arm64 --rm -i ghcr.io/${{ github.actor }}/armhpctrial:latest gcc -dumpfullversion > gcc.out
          echo "::set-output name=gcc::$(cat gcc.out)"

      - name: Get GFortran version
        id: get_gfortran_ver
        run: |
          docker run --platform arm64 --rm -i ghcr.io/${{ github.actor }}/armhpctrial:latest gfortran -dumpfullversion > gfortran.out
          echo "::set-output name=gfortran::$(cat gfortran.out)"

      - name: Get OpenMPI version
        id: get_openmpi_ver
        run: |
          docker run --platform arm64 --rm -i ghcr.io/${{ github.actor }}/armhpctrial:latest mpirun --version | awk -F " " '{print $4}' > openmpi.out
          echo "::set-output name=openmpi::$(cat openmpi.out)"

      - name: Get Python version
        id: get_python_ver
        run: |
          docker run --platform arm64 --rm -i ghcr.io/${{ github.actor }}/armhpctrial:latest python3 --version | awk -F " " '{print $2}' > python.out
          echo "::set-output name=python::$(cat python.out)"

      - name: Get NumPy version
        id: get_numpy_ver
        run: |
          docker run --platform arm64 --rm -i ghcr.io/${{ github.actor }}/armhpctrial:latest python3 -c 'import numpy; print(numpy.version.version)' > numpy.out
          echo "::set-output name=numpy::$(cat numpy.out)"

      - name: Get SciPy version
        id: get_scipy_ver
        run: |
          docker run --platform arm64 --rm -i ghcr.io/${{ github.actor }}/armhpctrial:latest python3 -c 'import scipy; print(scipy.version.version)' > scipy.out
          echo "::set-output name=scipy::$(cat scipy.out)"

      - name: Get MPI4Py version
        id: get_mpi4py_ver
        run: |
          docker run --platform arm64 --rm -i ghcr.io/${{ github.actor }}/armhpctrial:latest python3 -c 'import mpi4py; print(mpi4py.__version__)' > mpi4py.out
          echo "::set-output name=mpi4py::$(cat mpi4py.out)"

      - name: Get BLAS version
        id: get_blas_ver
        run: |
          docker run --platform arm64 --rm -i ghcr.io/${{ github.actor }}/armhpctrial:latest dpkg-query -l | grep blas3 | awk -F " " '{print $3}' | awk -F "-" '{print $1}' > blas.out
          echo "::set-output name=blas::$(cat blas.out)"


  badge:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    needs: get_image
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Update badge
        run: |
          mkdir -p .github/badges
          cd .github/badges
          rm -f *.svg
          curl -o gcc.svg https://img.shields.io/badge/gcc-${{ needs.get_image.outputs.gcc }}-blue
          curl -o gfortran.svg https://img.shields.io/badge/gfortran-${{ needs.get_image.outputs.gfortran }}-blue
          curl -o openmpi.svg https://img.shields.io/badge/openmpi-${{ needs.get_image.outputs.openmpi }}-blue
          curl -o python.svg https://img.shields.io/badge/python-${{ needs.get_image.outputs.python }}-blue
          curl -o numpy.svg https://img.shields.io/badge/numpy-${{ needs.get_image.outputs.numpy }}-blue
          curl -o mpi4py.svg https://img.shields.io/badge/mpi4py-${{ needs.get_image.outputs.mpi4py }}-blue
          curl -o blas.svg https://img.shields.io/badge/blas-${{ needs.get_image.outputs.blas }}-blue
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add *.svg
          if git commit -m "Update badges"; then
            git push
          fi
